FROM centos:7

ARG VERSION
ARG RELEASE=1
ARG ART_URL
ARG ART_USER
ARG ART_PASS
ARG ART_REPO

ENV BUILDPATH='/brotli'

RUN yum install -y git gzip unzip wget rpmdevtools rpm-build kernel-headers\
  curl libxslt-devel gd-devel GeoIP-devel openssh-clients libtool automake\
  gcc libc-devel make cmake openssl-devel pcre-devel zlib-devel autoconf\
  && yum clean all

RUN git checkout $VERSION \
  && mkdir out && cd out && ../configure-cmake \
  && make

WORKDIR $BUILDPATH/out/
RUN ls -lha

RUN tar -z -c --transform 's,^,/brotli/,' -f brotli-$VERSION.tar.gz brotli db/ proxyx-migrate

RUN rpmbuild -v -bb \
  --define "_sourcedir $(pwd)" \
  --define "_rpmdir $(pwd)" \
  --define "_topdir /tmp/rpmbuild" \
  --define "version $VERSION" \
  --define "release $RELEASE" \
  brotli.spec

RUN curl -u$ART_USER:$ART_PASS -XPUT $ART_URL/artifactory/$ART_REPO/x86_64/brotli-$VERSION-$RELEASE.x86_64.rpm -T x86_64/brotli-$VERSION-$RELEASE.x86_64.rpm
